# check the source file for basic characteristics
- src/neuralnetwork.py:
    - description: Ensure that main.py file exists in the src/ directory
      check: ConfirmFileExists
    - description: Complete all TODOs, remove the TODO markers in the main.py
      check: MatchFileFragment
      options:
        fragment: TODO
        count: 0
        exact: true

# check the technical writing for various characteristics
- writing/report.md:
    - description: Ensure that report.md file exists in the writing/ directory
      check: ConfirmFileExists
    - description: Write a minimum number of meaningful words (300) in the report
      check: CountFileWords
      options:
        count: 200
        exact: false
    - description: Complete all TODOs, remove the TODO markers in the report.md
      check: MatchFileFragment
      options:
        fragment: TODO
        count: 0
        exact: true
    - description: Ensure the report contains at least three images
      check: MatchFileFragment
      options:
        fragment: "!["
        count: 3
        exact: false

# check the dataset file for existence
- src/data/data.csv:
    - description: Ensure that data.csv file exists in the src/data/ directory
      check: ConfirmFileExists

# count number of commits in the GitHub repository
- description: Have at least a specific minimum number of commits (6) in repository
  check: CountCommits
  options:
    count: 6
